apiVersion: v1
kind: Service
metadata:
  name: validador-final-frontend
  namespace: validador-final
spec:
  type: ClusterIP
  selector:
    app: validador-final-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
